apiVersion: ipam.nephio.org/v1alpha1
kind: IPPrefix
metadata:
  name: sample-n4-net-prefix1
  labels:
    nephio.org/gateway: "true"
spec:
  prefix: 192.168.1.1/24
  network: sample-n4-net
  networkInstance: sample-vpc
