apiVersion: ipam.nephio.org/v1alpha1
kind: IPPrefix
metadata:
  name: us-central1.edge2.net1.prefix1
spec:
  kind: network
  networkInstance: vpc2
  prefix: 10.0.1.1/24
  labels:
    nephio.org/gateway: "true"
    nephio.org/region: us-central1
    nephio.org/site: edge2
    nephio.org/network-name: net1